### ISSUE TITLE
No licence specified

### ISSUE THREAD

**Issue by LachlanGunn** [ZenGo-X/dlog-verifiable-enc#5]
Thanks for this interesting library.  This code doesn't have any licence specified, unlike the other ZenGo-X repositories that I have looked at.  Is this intentional, or should it be GPL3 like your other published code?

**Comment by omershlo** [comment]
Thank you @LachlanGunn ! 
you assume GPLv3 is the right license , I will open an issue to add one.

**Comment by LachlanGunn** [comment]
Thanks very much for the super-quick reply.  FYI, the same is true also for for ZenGo-X/JugglingSwap.

**Comment by omershlo** [comment]
thanks ! 
cc: @oleiba

**Comment by omershlo** [comment]
done
