### ISSUE TITLE
Native API

### ISSUE THREAD

**Issue by LachlanGunn** [ZenGo-X/dlog-verifiable-enc#6]
I would like to use this code in a native Rust project, so am planning to do some refactoring to separate the cryptographic code from the Javascript API.

Is this something that you would be interested in incorporating upstream, or do you prefer to keep the focus on the Javascript and avoid feature-gating?

**Comment by omershlo** [comment]
did you consider using something like https://github.com/ZenGo-X/centipede/blob/master/src/juggling/proof_system.rs#L314 directly ?

**Comment by LachlanGunn** [comment]
Thanks.  I hadn't seen that, but you might be right that it is easier to take the code from there for the time being, so I'll give that a try.
